import abc
import requests
from typing import Dict, Any, Optional

# Assuming config.py is in the same directory or a parent directory accessible via relative import
# Adjust the import path if your project structure differs significantly.
try:
    from ..config import Config
except ImportError:
    # Fallback for standalone execution or different structures
    class Config:
        """Mock Config class for standalone testing if config.py is not found."""
        LLM_API_KEYS: Dict[str, str] = {
            "openai": "mock_openai_key",
            "anthropic": "mock_anthropic_key",
        }
        LLM_ENDPOINTS: Dict[str, str] = {
            "openai": "https://api.openai.com/v1/chat/completions",
            "anthropic": "https://api.anthropic.com/v1/messages",
        }
        DEFAULT_LLM_PROVIDER: str = "openai"
        DEFAULT_LLM_MODEL: str = "gpt-4-turbo-preview"


class LLMClient(abc.ABC):
    """
    Abstract base class for interacting with different Large Language Model (LLM) APIs.
    Defines the common interface for sending prompts and receiving responses.
    """

    def __init__(self, config: Config):
        """
        Initializes the LLMClient with configuration.

        Args:
            config: The global configuration object.
        """
        self.config = config

    @abc.abstractmethod
    def generate_response(self, prompt: str, model: str, system_message: str = None, **kwargs: Any) -> str:
        """
        Generates a text response from the LLM based on the provided prompt.

        Args:
            prompt: The input prompt to send to the LLM.
            model: The specific LLM model to use (e.g., "gpt-4", "claude-3-opus-20240229").
            **kwargs: Additional arguments specific to the LLM provider (e.g., temperature, max_tokens).

        Returns:
            The text response generated by the LLM.

        Raises:
            NotImplementedError: If the method is not implemented by a concrete subclass.
            LLMAPIError: If an error occurs during the API call.
        """
        pass


class LLMAPIError(Exception):
    """Custom exception for LLM API related errors."""
    pass


class OpenAIClient(LLMClient):
    """
    Concrete implementation for interacting with the OpenAI API.
    """

    def __init__(self, config: Config):
        super().__init__(config)
        self.api_key = getattr(config, 'openai_api_key', None) or getattr(config, 'LLM_API_KEYS', {}).get("openai")
        self.api_endpoint = getattr(config, 'LLM_ENDPOINTS', {}).get("openai", {}).get("url", "https://api.openai.com/v1/chat/completions")
        if not self.api_key:
            raise ValueError("OpenAI API key not found in configuration.")
        if not self.api_endpoint:
            raise ValueError("OpenAI API endpoint not found in configuration.")

    def generate_response(self, prompt: str, model: str = "gpt-4-turbo-preview", system_message: str = None, **kwargs: Any) -> str:
        """
        Sends a prompt to the OpenAI API and returns the generated response.

        Args:
            prompt: The input prompt.
            model: The OpenAI model to use. Defaults to "gpt-4-turbo-preview".
            **kwargs: Additional parameters for the OpenAI API (e.g., temperature, max_tokens).

        Returns:
            The text content of the response.

        Raises:
            LLMAPIError: If the API call fails or returns an error.
        """
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        messages = []
        if system_message:
            messages.append({"role": "system", "content": system_message})
        messages.append({"role": "user", "content": prompt})
        payload = {
            "model": model,
            "messages": messages,
            **kwargs,  # Include any additional parameters like temperature, max_tokens, etc.
        }

        try:
            response = requests.post(self.api_endpoint, headers=headers, json=payload, timeout=60)
            response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
            data = response.json()

            if "choices" in data and data["choices"]:
                return data["choices"][0].get("message", {}).get("content", "")
            else:
                raise LLMAPIError(f"OpenAI API returned an unexpected response structure: {data}")

        except requests.exceptions.RequestException as e:
            raise LLMAPIError(f"OpenAI API request failed: {e}") from e
        except Exception as e:
            raise LLMAPIError(f"An unexpected error occurred during OpenAI API call: {e}") from e


class AnthropicClient(LLMClient):
    """
    Concrete implementation for interacting with the Anthropic API (Claude).
    """

    def __init__(self, config: Config):
        super().__init__(config)
        self.api_key = getattr(config, 'anthropic_api_key', None) or getattr(config, 'LLM_API_KEYS', {}).get("anthropic")
        self.api_endpoint = getattr(config, 'LLM_ENDPOINTS', {}).get("anthropic", {}).get("url", "https://api.anthropic.com/v1/messages")
        if not self.api_key:
            raise ValueError("Anthropic API key not found in configuration.")
        if not self.api_endpoint:
            raise ValueError("Anthropic API endpoint not found in configuration.")

    def generate_response(self, prompt: str, model: str = "claude-3-opus-20240229", system_message: str = None, **kwargs: Any) -> str:
        """
        Sends a prompt to the Anthropic API and returns the generated response.

        Args:
            prompt: The input prompt.
            model: The Anthropic model to use. Defaults to "claude-3-opus-20240229".
            **kwargs: Additional parameters for the Anthropic API (e.g., temperature, max_tokens).

        Returns:
            The text content of the response.

        Raises:
            LLMAPIError: If the API call fails or returns an error.
        """
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",  # Specify Anthropic API version
            "Content-Type": "application/json",
        }
        payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            **kwargs,  # Include any additional parameters like temperature, max_tokens, etc.
        }
        if system_message:
            payload["system"] = system_message

        try:
            response = requests.post(self.api_endpoint, headers=headers, json=payload, timeout=60)
            response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
            data = response.json()

            if "content" in data and data["content"]:
                # Anthropic's response content can be a list of content blocks
                # We'll try to extract text content from the first block
                for block in data["content"]:
                    if block.get("type") == "text":
                        return block.get("text", "")
                raise LLMAPIError(f"Anthropic API response content did not contain text: {data}")
            else:
                raise LLMAPIError(f"Anthropic API returned an unexpected response structure: {data}")

        except requests.exceptions.RequestException as e:
            raise LLMAPIError(f"Anthropic API request failed: {e}") from e
        except Exception as e:
            raise LLMAPIError(f"An unexpected error occurred during Anthropic API call: {e}") from e


class GroqClient(LLMClient):
    """
    Concrete implementation for interacting with the Groq Cloud API.
    Fast, free-tier friendly LLM provider with competitive models.
    """

    def __init__(self, config: Config):
        super().__init__(config)
        # Try to get groq_api_key from config object
        self.api_key = getattr(config, 'groq_api_key', None) or getattr(config, 'LLM_API_KEYS', {}).get("groq")
        self.api_endpoint = "https://api.groq.com/openai/v1/chat/completions"
        if not self.api_key:
            raise ValueError("Groq API key not found in configuration.")

    def generate_response(self, prompt: str, model: str = "mixtral-8x7b-32768", system_message: str = None, **kwargs: Any) -> str:
        """
        Sends a prompt to the Groq API and returns the generated response.

        Args:
            prompt: The input prompt.
            model: The Groq model to use. Defaults to "mixtral-8x7b-32768".
            system_message: Optional system-level instruction.
            **kwargs: Additional parameters for the Groq API (e.g., temperature, max_tokens).

        Returns:
            The text content of the response.

        Raises:
            LLMAPIError: If the API call fails or returns an error.
        """
        # Strip provider prefix if present (e.g., "groq-mixtral-8x7b-32768" -> "mixtral-8x7b-32768")
        if model.startswith("groq-"):
            model = model[5:]
        # Validate and clean model name
        if hasattr(self.config, 'get_clean_model_name'):
            model = self.config.get_clean_model_name(model)
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        messages = []
        if system_message:
            messages.append({"role": "system", "content": system_message})
        messages.append({"role": "user", "content": prompt})
        payload = {
            "model": model,
            "messages": messages,
            "temperature": kwargs.get("temperature", 0.7),
            "max_tokens": kwargs.get("max_tokens", 1024),
        }

        try:
            response = requests.post(self.api_endpoint, headers=headers, json=payload, timeout=60)
            response.raise_for_status()
            data = response.json()

            if "choices" in data and data["choices"]:
                return data["choices"][0].get("message", {}).get("content", "")
            else:
                raise LLMAPIError(f"Groq API returned an unexpected response structure: {data}")

        except requests.exceptions.RequestException as e:
            raise LLMAPIError(f"Groq API request failed: {e}") from e
        except Exception as e:
            raise LLMAPIError(f"An unexpected error occurred during Groq API call: {e}") from e


# Factory function to get the appropriate client
def get_llm_client(provider: str, config: Config) -> LLMClient:
    """
    Factory function to retrieve an LLM client based on the provider name.

    Args:
        provider: The name of the LLM provider (e.g., "openai", "anthropic").
        config: The global configuration object.

    Returns:
        An instance of a concrete LLMClient subclass.

    Raises:
        ValueError: If the provider is not supported.
    """
    provider_map = {
        "openai": OpenAIClient,
        "anthropic": AnthropicClient,
        "groq": GroqClient,
        # Add other providers here as needed
    }

    client_class = provider_map.get(provider.lower())
    if not client_class:
        raise ValueError(f"Unsupported LLM provider: {provider}. Supported providers are: {list(provider_map.keys())}")

    return client_class(config)