"""
ForgeGuard AI — Social Swarm (Social Engineering Simulation Generator)
═══════════════════════════════════════════════════════════════════════════
PURPOSE: Generates social-engineering templates for AUTHORISED security
         awareness training, red-team exercises, and internal purple-team
         simulations ONLY.

REQUIRES: Signed Authorisation Token (FORGEGUARD_SIM_AUTH) before any
          template is emitted.

COMPLIANCE: Aligned with the ForgeGuard Target Verification Protocol.
            All generated content is watermarked and traceable.

WARNING: This module is disabled by default. It requires an explicit,
         cryptographically-signed authorisation token that ties the output
         to a specific approved engagement. Unauthorised use violates the
         ForgeGuard Acceptable Use Policy and may constitute a criminal
         offence under the Computer Fraud and Abuse Act (CFAA 18 U.S.C.
         § 1030), the UK Computer Misuse Act 1990, and equivalent statutes
         worldwide.
═══════════════════════════════════════════════════════════════════════════
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
import textwrap
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from enum import Enum, auto
from typing import Any, Callable, Dict, List, Optional, Set, Tuple
from uuid import uuid4


# ═══════════════════════════════════════════════════════════════════════════
# Authorisation & Watermarking
# ═══════════════════════════════════════════════════════════════════════════

class AuthorisationState(Enum):
    """Current authorisation state of the module."""
    LOCKED     = auto()   # No token provided — module refuses to emit content
    VALIDATED  = auto()   # Token accepted — module operational
    EXPIRED    = auto()   # Token was valid but has timed out
    INVALID    = auto()   # Token failed verification

@dataclass(frozen=True)
class EngagementToken:
    """
    Immutable engagement authorisation token.
    Generated by ForgeGuard's admin panel and signed with the organisation's
    private key. This token pins output to a specific approved engagement.
    """
    engagement_id: str
    organisation_id: str
    authorised_by: str           # Identity of the approving security lead
    scope_of_work: str           # e.g. "Q3 2026 Internal Red Team — Developer Phishing"
    target_domain: str           # The domain owned & verified via Target Verification Protocol
    issued_at: str               # ISO 8601
    expires_at: str              # ISO 8601
    signature: str               # HMAC-SHA256(engagement_id|org_id|expires_at, org_secret)

    def is_expired(self) -> bool:
        expire = datetime.fromisoformat(self.expires_at.replace("Z", "+00:00"))
        return datetime.now(timezone.utc) > expire

    def to_watermark(self) -> str:
        """Produces a compact watermark embedded in every generated template."""
        return (
            f"FORGEGUARD-TRACE:{self.engagement_id}:{self.organisation_id}:"
            f"{self.authorised_by}:{self.target_domain}"
        )

class AuthorisationGuard:
    """
    Enforces that the module cannot produce social-engineering content
    without a valid, unexpired engagement token signed by the organisation.
    """

    def __init__(self, organisation_secret: Optional[str] = None):
        self._organisation_secret = organisation_secret or os.environ.get(
            "FORGEGUARD_ORG_SECRET", ""
        )
        self._current_token: Optional[EngagementToken] = None
        self._state = AuthorisationState.LOCKED

    # ── Token Verification ──

    def verify_and_activate(self, token_dict: Dict[str, str]) -> AuthorisationState:
        """Verify a token dict (as received from the ForgeGuard admin API) and activate if valid."""
        if not self._organisation_secret:
            self._state = AuthorisationState.LOCKED
            return self._state

        try:
            token = EngagementToken(**token_dict)
        except TypeError:
            self._state = AuthorisationState.INVALID
            return self._state

        # Check expiry
        if token.is_expired():
            self._state = AuthorisationState.EXPIRED
            return self._state

        # Verify signature
        payload = f"{token.engagement_id}|{token.organisation_id}|{token.expires_at}"
        expected = hmac.new(
            self._organisation_secret.encode(),
            payload.encode(),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(expected, token.signature):
            self._state = AuthorisationState.INVALID
            return self._state

        self._current_token = token
        self._state = AuthorisationState.VALIDATED
        return self._state

    @property
    def is_authorised(self) -> bool:
        return self._state == AuthorisationState.VALIDATED

    @property
    def watermark(self) -> str:
        if not self._current_token:
            return "FORGEGUARD-TRACE:UNAUTHORISED"
        return self._current_token.to_watermark()

    def guard(self, fn: Callable) -> Callable:
        """Decorator that blocks execution unless authorised."""
        def wrapper(*args, **kwargs):
            if not self.is_authorised:
                raise PermissionError(
                    "Social Swarm is LOCKED. Provide a valid ForgeGuard Engagement Token "
                    "via verify_and_activate() before generating any simulation content. "
                    "This module is for AUTHORISED security training only."
                )
            result = fn(*args, **kwargs)
            # Embed watermark in string results
            if isinstance(result, str):
                result = (
                    f"{'─'*72}\n"
                    f"FORGEGUARD SOCIAL SWARM — AUTHORISED SIMULATION CONTENT\n"
                    f"Engagement: {self._current_token.engagement_id}\n"
                    f"Authorised by: {self._current_token.authorised_by}\n"
                    f"Target domain: {self._current_token.target_domain}\n"
                    f"Watermark: {self.watermark}\n"
                    f"Generated: {datetime.now(timezone.utc).isoformat()}\n"
                    f"THIS CONTENT IS FOR AUTHORISED SECURITY TRAINING ONLY.\n"
                    f"{'─'*72}\n\n"
                ) + result
            return result
        return wrapper


# ═══════════════════════════════════════════════════════════════════════════
# Data Models
# ═══════════════════════════════════════════════════════════════════════════

class Platform(Enum):
    """Digital platforms where pretexting scenarios may be deployed."""
    LINKEDIN = "linkedin"
    EMAIL    = "email"
    SLACK    = "slack"
    TEAMS    = "teams"
    DISCORD  = "discord"
    GITHUB   = "github"
    TWITTER  = "twitter"

class EmployeeRole(Enum):
    """Roles that may be targeted in a simulation (for scenario tailoring)."""
    DEVELOPER           = auto()
    DEVOPS_ENGINEER     = auto()
    SRE                 = auto()
    SECURITY_ENGINEER   = auto()
    IT_HELPDESK         = auto()
    ENGINEERING_MANAGER = auto()
    CTO                 = auto()
    DATA_SCIENTIST      = auto()
    PRODUCT_MANAGER     = auto()
    HR                  = auto()

class UrgencyLevel(Enum):
    LOW    = auto()
    MEDIUM = auto()
    HIGH   = auto()
    CRITICAL = auto()

@dataclass
class CompanyMetadata:
    """
    Target company metadata as produced by the OSINT Scout.
    Populated via the Target Verification Protocol — the requesting
    organisation MUST have verified domain ownership.
    """
    # ── Verified identity ──
    company_name: str
    primary_domain: str                     # Verified via DNS TXT record
    verified_at: str                        # ISO 8601 timestamp

    # ── OSINT-derived (publicly available) ──
    industry: str                           # e.g. "fintech", "healthtech", "SaaS"
    employee_count_range: str               # e.g. "50-200", "200-1000"
    tech_stack_public: List[str] = field(default_factory=list)  # e.g. ["AWS", "Python", "FastAPI", "OpenAI"]
    public_repos: List[str] = field(default_factory=list)       # GitHub org repos
    key_employees_public: List[Dict[str, str]] = field(default_factory=list)
    # ^^ [{"name": "Jane Doe", "role": "VP Engineering", "linkedin": "..."}]
    recent_news: List[str] = field(default_factory=list)        # press releases, blog posts
    social_media_presence: Dict[str, str] = field(default_factory=dict)  # platform -> handle
    subsidiaries: List[str] = field(default_factory=list)
    known_vendors: List[str] = field(default_factory=list)      # from job postings / case studies
    conference_presence: List[str] = field(default_factory=list)  # talks, sponsorships

    # ── Internal (populated by ForgeGuard modules) ──
    exposed_api_endpoints: List[str] = field(default_factory=list)
    llm_provider: str = ""
    authentication_provider: str = ""       # e.g. "Auth0", "Clerk", "Okta"

@dataclass
class SocialTemplate:
    """A single social-engineering simulation template."""
    template_id: str
    category: str                           # "phishing_email", "vishing_script", "pretexting"
    platform: Platform
    title: str
    target_role: EmployeeRole
    urgency: UrgencyLevel
    scenario_context: str                   # Why this scenario is plausible for this company
    content: str                            # The actual template text
    red_flags: List[str]                    # What trainees should spot
    detection_tips: str                     # For the training debrief
    owasp_reference: str                    # OWASP Top 10 for LLMs or Social Engineering reference
    watermark: str

@dataclass
class SocialExposureMap:
    """
    The complete output: all generated simulation templates, tied to a
    specific verified target and engagement.
    """
    engagement_id: str
    organisation_id: str
    target_company: CompanyMetadata
    generated_at: str
    expires_at: str
    templates: List[SocialTemplate]
    summary_statistics: Dict[str, int]
    training_deployment_guide: str
    disclaimer: str


# ═══════════════════════════════════════════════════════════════════════════
# OSINT Context Analyser
# ═══════════════════════════════════════════════════════════════════════════

class OSINTContextAnalyser:
    """
    Analyses CompanyMetadata to identify plausible pretexts, impersonation
    targets, and contextual hooks that make social-engineering scenarios
    believable — so the training is realistic and effective.
    """

    @staticmethod
    def derive_impersonation_targets(meta: CompanyMetadata) -> List[Dict[str, str]]:
        """
        Identify which real people/roles an attacker would impersonate
        based on public information. Used to make phishing scenarios realistic.
        """
        targets: List[Dict[str, str]] = []

        # From known employees
        for emp in meta.key_employees_public:
            if any(r in emp.get("role", "").lower() for r in
                   ["cto", "vp engineering", "head of engineering", "ceo", "founder"]):
                targets.append({
                    "name": emp.get("name", "Unknown"),
                    "role": emp.get("role", "Leadership"),
                    "source": "public_linkedin",
                    "impersonation_value": "high",
                })

        # Fallback: construct plausible authority figures
        if not targets:
            targets.append({
                "name": f"CTO @ {meta.company_name}",
                "role": "Chief Technology Officer",
                "source": "inferred_from_job_board",
                "impersonation_value": "high",
            })

        return targets

    @staticmethod
    def derive_tech_pretexts(meta: CompanyMetadata) -> List[str]:
        """Build a list of plausible technical pretexts based on the public tech stack."""
        pretexts: List[str] = []

        if any("openai" in t.lower() or "gpt" in t.lower() for t in meta.tech_stack_public):
            pretexts.append("OpenAI API key rotation / billing issue")
        if any("aws" in t.lower() for t in meta.tech_stack_public):
            pretexts.append("AWS IAM credential expiry / CloudTrail alert")
        if any("github" in t.lower() for t in meta.tech_stack_public):
            pretexts.append("GitHub PAT (Personal Access Token) audit")
        if any("docker" in t.lower() or "kubernetes" in t.lower() for t in meta.tech_stack_public):
            pretexts.append("Docker Hub / container registry credential refresh")
        if any("auth0" in t.lower() or "okta" in t.lower() or "clerk" in t.lower()
               for t in [meta.authentication_provider] + meta.tech_stack_public):
            pretexts.append(f"{meta.authentication_provider} SSO certificate expiry")

        if not pretexts:
            pretexts.append("CI/CD pipeline secret rotation")
            pretexts.append("Cloud provider API key audit")

        return pretexts

    @staticmethod
    def derive_temporal_hooks(meta: CompanyMetadata) -> List[str]:
        """Find time-sensitive hooks that add urgency to scenarios."""
        hooks: List[str] = []
        now = datetime.now(timezone.utc)

        # Conference season
        if meta.conference_presence:
            hooks.append(
                f"Upcoming conference presence: {meta.conference_presence[0]} — "
                f"attackers often target speakers/sponsors pre-conference"
            )

        # News-driven
        for news in meta.recent_news[:3]:
            if "funding" in news.lower() or "series" in news.lower():
                hooks.append(f"Recent funding announcement ({news[:80]}...) — heightened targeting risk")
            if "launch" in news.lower() or "release" in news.lower():
                hooks.append(f"Recent product launch ({news[:80]}...) — support-team impersonation vector")

        # Default seasonal hooks
        month = now.month
        if month in (11, 12):
            hooks.append("Holiday season — reduced staffing, increased phishing")
        if month in (6, 7, 8):
            hooks.append("Summer vacation period — skeleton crew risk")

        return hooks

    @staticmethod
    def derive_vendor_pretexts(meta: CompanyMetadata) -> List[str]:
        """Build vendor-impersonation scenarios from known vendors."""
        pretexts: List[str] = []
        for vendor in meta.known_vendors[:5]:
            pretexts.append(f"Security alert from {vendor} — urgent patch required")
        if not pretexts:
            pretexts.append("Cloud provider security notification")
        return pretexts


# ═══════════════════════════════════════════════════════════════════════════
# Template Builders
# ═══════════════════════════════════════════════════════════════════════════

class PhishingEmailBuilder:
    """
    Generates realistic phishing email templates targeting developers.
    Each template includes red flags and detection tips for training debriefs.
    """

    @staticmethod
    def build_1_api_key_audit(meta: CompanyMetadata, watermark: str,
                               impersonation: Dict[str, str]) -> SocialTemplate:
        """Template 1: Fake API key audit from 'CTO'."""

        cto_name = impersonation.get("name", f"CTO @ {meta.company_name}")
        domain = meta.primary_domain
        provider = meta.llm_provider or "OpenAI"

        content = textwrap.dedent(f"""\
        From: "{cto_name}" <cto@{domain}>
        To: engineering@{domain}
        Subject: [URGENT] {provider} API Key Audit — Compliance Deadline Today

        Team,

        Our {provider} billing dashboard flagged several API keys with anomalous
        usage patterns overnight. Finance needs us to verify every active key by
        5 PM ET today, or they'll suspend our organisational account to prevent
        overage charges.

        This is time-critical. Our Series B investors are reviewing our infra
        costs this week, and a $40K+ overage would be a board-level incident.

        Please complete the audit in two steps:

        1.  Go to our internal API key registry (link below) and confirm your
            keys are listed:
            https://{domain}/api-key-registry

        2.  If any of your keys are missing, reply to this email with:
            • The key prefix (first 8 characters only — never share full keys!)
            • The project it's associated with
            • Monthly token usage estimate

        I'll reconcile everything tonight and send the report to Finance.

        — {cto_name}
          Chief Technology Officer
          {meta.company_name}

        ---
        This email was sent via {meta.company_name} Internal Audit System.
        Ref: AUD-{uuid4().hex[:8].upper# (Continuing from where your file cut off...)
        return SocialTemplate(
            template_id=f"PHISH-{uuid4().hex[:6]}",
            category="phishing_email",
            platform=Platform.EMAIL,
            title="Internal API Key Compliance Audit",
            target_role=EmployeeRole.DEVELOPER,
            urgency=UrgencyLevel.HIGH,
            scenario_context="Leverages authority (CTO) and investor pressure (Series B) to bypass standard verification.",
            content=content,
            red_flags=[
                "Requests secret data via email (out-of-band)",
                "Creates artificial urgency related to funding/billing",
                "Domain spoofing risk (cto@ vs official security portal)"
            ],
            detection_tips="Always verify out-of-band requests for secrets via internal Slack/Teams before replying.",
            owasp_reference="OWASP LLM06: Sensitive Information Disclosure",
            watermark=watermark
        )

    @staticmethod
    def build_2_it_helpdesk_vishing(meta: CompanyMetadata, watermark: str) -> SocialTemplate:
        """Template 2: IT Helpdesk impersonation script (Vishing)."""
        content = textwrap.dedent(f"""
        [SIMULATED CALL SCRIPT]
        AGENT: 'Hi, this is Mark from the Global IT Helpdesk. We’re seeing a persistent 
               login loop on your {meta.authentication_provider} account that’s 
               tripping our DDoS sensors.'
        AGENT: 'I need to push a manual sync to your workstation. You’re about to 
               get a push notification on your phone. Can you go ahead and 
               approve that so we can clear the alert?'
        [IF TARGET ASKS FOR VERIFICATION]: 
        AGENT: 'I can send you my employee ID, it’s IT-9928. We’re in a bit of a 
               rush because this is affecting the {meta.company_name} production 
               deploy. Can you just hit approve on that MFA for me?'
        """)
        return SocialTemplate(
            template_id=f"VISH-{uuid4().hex[:6]}",
            category="vishing_script",
            platform=Platform.EMAIL,
            title="MFA Fatigue / Helpdesk Impersonation",
            target_role=EmployeeRole.IT_HELPDESK,
            urgency=UrgencyLevel.CRITICAL,
            scenario_context="Exploits 'MFA Fatigue' and the helpful nature of support staff.",
            content=content,
            red_flags=["Unsolicited call from IT", "Pressure to approve MFA without a ticket", "Artificial urgency"],
            detection_tips="IT will never call to ask you to 'just approve' an MFA push without a valid ticket number.",
            owasp_reference="Social Engineering: MFA Bypass",
            watermark=watermark
        )

# ═══════════════════════════════════════════════════════════════════════════
# The Swarm Orchestrator
# ═══════════════════════════════════════════════════════════════════════════

class SocialSwarm:
    def __init__(self, guard: AuthorisationGuard):
        self.guard = guard
        self.builder = PhishingEmailBuilder()

    @AuthorisationGuard().guard
    def generate_exposure_map(self, meta: CompanyMetadata) -> SocialExposureMap:
        impersonation = OSINTContextAnalyser.derive_impersonation_targets(meta)[0]
        
        templates = [
            self.builder.build_1_api_key_audit(meta, self.guard.watermark, impersonation),
            self.builder.build_2_it_helpdesk_vishing(meta, self.guard.watermark)
        ]

        return SocialExposureMap(
            engagement_id=self.guard._current_token.engagement_id,
            organisation_id=self.guard._current_token.organisation_id,
            target_company=meta,
            generated_at=datetime.now(timezone.utc).isoformat(),
            expires_at=(datetime.now(timezone.utc) + timedelta(days=7)).isoformat(),
            templates=templates,
            summary_statistics={"total_vectors": len(templates), "critical_urgency": 1},
            training_deployment_guide="Deploy via internal phishing simulation tool. Track click-through rates.",
            disclaimer="FOR AUTHORISED TRAINING ONLY."
        )